// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: CrossBridge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockChain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainName    string `protobuf:"bytes,1,opt,name=ChainName,proto3" json:"ChainName,omitempty"`
	ChainVersion string `protobuf:"bytes,2,opt,name=ChainVersion,proto3" json:"ChainVersion,omitempty"`
}

func (x *BlockChain) Reset() {
	*x = BlockChain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CrossBridge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockChain) ProtoMessage() {}

func (x *BlockChain) ProtoReflect() protoreflect.Message {
	mi := &file_CrossBridge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockChain.ProtoReflect.Descriptor instead.
func (*BlockChain) Descriptor() ([]byte, []int) {
	return file_CrossBridge_proto_rawDescGZIP(), []int{0}
}

func (x *BlockChain) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *BlockChain) GetChainVersion() string {
	if x != nil {
		return x.ChainVersion
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Status  int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CrossBridge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_CrossBridge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_CrossBridge_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Address) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CrossBridge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From     *BlockChain `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To       *BlockChain `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Contract *Address    `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
}

func (x *CrossBridge) Reset() {
	*x = CrossBridge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CrossBridge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossBridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossBridge) ProtoMessage() {}

func (x *CrossBridge) ProtoReflect() protoreflect.Message {
	mi := &file_CrossBridge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossBridge.ProtoReflect.Descriptor instead.
func (*CrossBridge) Descriptor() ([]byte, []int) {
	return file_CrossBridge_proto_rawDescGZIP(), []int{2}
}

func (x *CrossBridge) GetFrom() *BlockChain {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CrossBridge) GetTo() *BlockChain {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *CrossBridge) GetContract() *Address {
	if x != nil {
		return x.Contract
	}
	return nil
}

var File_CrossBridge_proto protoreflect.FileDescriptor

var file_CrossBridge_proto_rawDesc = []byte{
	0x0a, 0x11, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x71, 0x0a, 0x0b, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x12,
	0x1f, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x1b, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x24, 0x0a,
	0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_CrossBridge_proto_rawDescOnce sync.Once
	file_CrossBridge_proto_rawDescData = file_CrossBridge_proto_rawDesc
)

func file_CrossBridge_proto_rawDescGZIP() []byte {
	file_CrossBridge_proto_rawDescOnce.Do(func() {
		file_CrossBridge_proto_rawDescData = protoimpl.X.CompressGZIP(file_CrossBridge_proto_rawDescData)
	})
	return file_CrossBridge_proto_rawDescData
}

var file_CrossBridge_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_CrossBridge_proto_goTypes = []interface{}{
	(*BlockChain)(nil),  // 0: BlockChain
	(*Address)(nil),     // 1: Address
	(*CrossBridge)(nil), // 2: CrossBridge
}
var file_CrossBridge_proto_depIdxs = []int32{
	0, // 0: CrossBridge.from:type_name -> BlockChain
	0, // 1: CrossBridge.to:type_name -> BlockChain
	1, // 2: CrossBridge.contract:type_name -> Address
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_CrossBridge_proto_init() }
func file_CrossBridge_proto_init() {
	if File_CrossBridge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CrossBridge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockChain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CrossBridge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CrossBridge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossBridge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CrossBridge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CrossBridge_proto_goTypes,
		DependencyIndexes: file_CrossBridge_proto_depIdxs,
		MessageInfos:      file_CrossBridge_proto_msgTypes,
	}.Build()
	File_CrossBridge_proto = out.File
	file_CrossBridge_proto_rawDesc = nil
	file_CrossBridge_proto_goTypes = nil
	file_CrossBridge_proto_depIdxs = nil
}
